ARG image
ARG image_tag

FROM $image:$image_tag

RUN yum -y update && yum clean all

RUN yum install -y \
  autoconf \
  # includes gcc and gcc-c++, the latter
  # is needed to build Erlang/OTP with a JIT
  clang \
  m4 \
  openssl-devel \
  ncurses-devel \
  rpm-build \
  rpmdevtools \
  rpmlint \
  tar \
  wget \
  zlib-devel \
  systemd-devel \
  make

RUN mkdir /build
CMD ["sh", "-c", "cd /build/pkg-build-dir && make"]
